config/routes.rb
Rails.application.routes.draw do
  resources :meetings do
    resources :comments
  end
  
  namespace :site do
    get 'meetings/index'
  end

  root to: 'meetings#index'


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :meetings, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    layout :layout_by_resource

    protected
  
    def layout_by_resource
      if devise_controller? && resource_name == :user
        "meeting_devise"
      else
        "application"
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user! # autenticar antes que alguém possa comentar quem não está logado.
    before_action :set_comment, only: [:edit, :update, :show, :destroy]
    before_action :set_meeting

    def new
        @comment = Comment.new
    end

    def create
        @comment = @meeting.comments.create(params[:comment].permit(:reply, :meeting_id))
        @comment.user_id = current_user.id
    
        respond_to do |format|
          if @comment.save
            format.html { redirect_to meeting_path(@meeting) }
            format.js # renders create.js.erb
          else
            format.html { redirect_to meeting_path(@meeting), notice: "Seu comentário não foi salvo. Por favor, tente novamente." }
            format.js
          end
        end
    end
    
    def destroy
        @comment = @meeting.comments.find(params[:id])
        @comment.destroy
        redirect_to meeting_path(@meeting)
    end


    private
  
    def set_meeting
        @meeting = Meeting.find(params[:meeting_id])
    end

    def set_comment
        @comment = Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:reply)
    end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = current_user.meetings.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @comment = Comment.new
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
    end
end

app/controllers/site/meeting_controller.rb
class Site::MeetingController < ApplicationController
  layout "site"
  def index
  end

  def data
    meetings = Meeting.all
    @meetings.user = current_user
 
    render :json => meetings.map {|meeting| {
               :id => meeting.id,
               :start_date => meeting.start_date.to_formatted_s(:db),
               :end_date => meeting.end_date.to_formatted_s(:db),
               :text => meeting.description,
               :user => meeting.user
           }}
  end

  def db_action
    mode = params["!nativeeditor_status"]
    id = params["id"]
    start_date = params["start_date"]
    end_date = params["end_date"]
    description = params["text"]
    user = params["user"]
 
    case mode
      when "inserted"
        meeting = Meeting.create :start_date => start_date, :end_date => end_date, 
                                :description => description, :user => user
        tid = meeting.id
 
      when "deleted"
        Meeting.find(id).destroy
        tid = id
 
      when "updated"
        meeting = Meeting.find(id)
        meeting.start_date = start_date
        meeting.end_date = end_date
        meeting.description = description
        meeting.user = user
        meeting.save
        tid = id
    end
 
    render :json => {
               :type => mode,
               :sid => id,
               :tid => tid,
           }
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  def new
    build_resource({})
    #resource.build_profile_member  // modificar para algo q tenha o nome
    respond_with self.resource
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(
          :sign_up,
          keys:[
              :email, :password, :password_confirmation,
              :name
          ]
      )
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController



    protected
        def after_sign_in_path_for(resource)
            meetings_path
        end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def devise_sign_in?
        params[:controller] == 'users/sessions' ? '' : 'display:none;'
    end

    def devise_sign_up?
        params[:controller] == 'users/registrations' ? '' : 'display:none;'
    end

    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end
    
    def author_of(record)
        user_signed_in? && current_user.id == record.user_id
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/site/meeting_helper.rb
module Site::MeetingHelper
end

app/views/comments/_comment.html.erb
<div class="flex items-start p-4 mt-4 border rounded">
  <div class="flex-1 pl-4 flex items-start justify-between">
    <div class="leading-normal">
      <p class="text-gray-700 text-xs"><%= comment.user.name %> comentou <%= time_ago_in_words(comment.created_at) %> atrás</p>
      <div class="text-gray-900"><%= sanitize comment.reply %></div>
    </div>

    <% if author_of(comment) %>
      <%= link_to "Delete", meeting_comment_path(comment.meeting, comment), method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-destroy" %>
    <% end %>
  </div>
</div> 

app/views/comments/_form.html.erb
<p class="text-sm text-gray-900 my-2">comentar como <%= current_user.name %></p>

<%= form_for([@meeting, @comment], remote: true) do |f| %>
  <div class="relative">
    <%= f.hidden_field :reply, class: "input h-32 border border-gray-600 resize-none", placeholder: "Adicione quaisquer notas ou respostas aqui" %>

    <trix-editor input="comment_reply" id="comment_reply_trix" class="h-32 p-4"></trix-editor>

    <%= f.submit class: "btn btn-small btn-secondary block w-full text-center mt-2 lg: mt-0 lg:text-left lg:pin-b lg:pin-r lg:mb-2 lg:mr-2 lg:w-auto lg:inline-flex" %>
  </div>
<% end %> 

app/views/comments/create.js.erb
var comments = document.getElementById("comments");
var commentField = document.getElementById("comment_reply");
var trixField = document.getElementById("comment_reply_trix");
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render(@comment)) %>");
commentField.value = "";
trixField.innerHTML = "";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app.name')  %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-gray-200">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <%= render partial: "layouts/site_shared/navigation" %>


    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html> 

app/views/layouts/meeting_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.name') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'login_device', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'login_device' %>


</head>

<body>
    <%= yield %>
</body>

</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= t('app.name') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

 <%= render partial: "layouts/site_shared/navigation" %>

 <%= yield %>

</body>
</html>

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to t('app.name'), "#", class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
                <% unless user_signed_in? %>
                    <li>
                        <%= link_to "#{t('top_menu.sign_in')}", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "#{t('top_menu.sign_up')}", new_user_registration_path %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Dashboard", meetings_path %>
                    </li>
                    <li>
                        <%= link_to "Schedule new session", new_meeting_path %>
                    </li>
                    <li>
                        <%= link_to current_user.name, "#" %>
                    </li>
                    <li>
                        <%= link_to "#{t('top_menu.logout')}", destroy_user_session_path, method: :delete %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting, class: "link" %>
    </div>
  <% end %>
<% end %> 

app/views/meetings/_form.html.erb
<div class="p-10 bg-white border border-gray-600 rounded">
  <%= form_with(model: meeting, local: true, class: "meeting-form") do |form| %>
    <% if meeting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(meeting.errors.count, "error") %> proibiu esta reunião de ser salva:</h2>

        <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h3 class="mb-4 text-center"><b>Informação da Reunião</b></h3>

    <div class="mb-6">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input"  %>
    </div>

    <div class="mb-6">
      <%= form.label :start_time, class: "label" %>
      <div class="flex items-center justify-between max-w-md">
        <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
      </div>
    </div>

    <div class="mb-6">
      <%= form.label :end_time, class: "label" %>
      <div class="flex items-center justify-between max-w-md">
        <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
      </div>
    </div>

    <hr class="border" />

    <%= form.submit class: "btn btn-primary text-base py-3 px-5" %>
    
  <% end %>
</div> 

app/views/meetings/_meetings_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-gray-500 text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-500 text-2xl mb-6">Parece que você ainda não agendou uma sessão</h1>
  <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-primary py-3 px-5" %>
</div> 

app/views/meetings/_meetings_landing.html.erb
<nav class="bg-white mb-4 shadow rounded-bl-lg">
  <ul id="nav-tab" class="tabs list-none flex">

    <li class="active" data-tab="calendar">
      <%= link_to "#calendar", class: "tab flex items-center" do %>
       <svg viewBox="0 0 20 20" width="16" height="16" class="fill-current text-gray-500 mr-2"><title>calendar</title><path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z"></path></svg>
       Calendario
      <% end %>
    </li>

     <li data-tab="all-meetings">
      <%= link_to "#all-meetings", class: "tab flex items-center" do %>
        <svg viewBox="0 0 20 20" class="fill-current text-gray-500 mr-2" width="16" height="16"><title>coffee</title><path d="M4 11H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h2V1h14v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm0-2V5H2v4h2zm-2 8v-1h18v1l-4 2H6l-4-2z"></path></svg>
      Todas As Reuniões
      <% end %>
    </li>

  </ul>
</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings" class="tab-panel">

     <h1>Reuniões</h1>

     <% meetings.each do |meeting| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-gray-500 mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to meeting.name, meeting, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(meeting.start_time) %> &ndash;
              <%= readable_time(meeting.end_time) %>
            </div>
          </div>
        </div>

        <%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Tem certeza? Não há reembolsos." }, class: "btn btn-destroy ml-4"  %>
     <% end %>
  </div>

  <div id="calendar" class="tab-panel active">
    <h2>Calendário de Reunião</h2>
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings  %>
    </div>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class="max-w-lg m-auto px-4">
  <h1 class="text-3xl mt-10">Editar sessões</h1>
  <p class="text-lg text-gray-900 mb-6">Modifique sua sessão de consultoria escolhendo o melhor horário para você abaixo.</p>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.meetings.any? %>
    <%= render "meetings_cta" %>
  <% else %>
    <%= render "meetings_landing", meetings: @meetings %>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="max-w-lg m-auto px-4">
  <h1 class="text-3xl mt-10 text-center">Agende uma nova sessão</h1>
  <p class="text-lg text-gray-900 mb-6">Agende uma nova sessão de consultoria escolhendo abaixo o melhor horário para você.</p>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/show.html.erb
<div class="max-w-lg my-12s m-auto">
  <div class="p-4 bg-white border border-gray-600 rounded">

    <div class="flex flex-wrap justify-between items-center mb-5">
      <h1><%= @meeting.name %></h1>
      <%= link_to "Cancel Meeting", meeting_path(@meeting), method: :delete, data: { confirm: "Você tem certeza que deseja cancelar? "}, class: "btn btn-destroy" %> 
    </div>

    <div class="border p-6 bg-gray-300 mb-5 flex items-center justify-between">
      <p class="border-2 py-3 px-4 border-indigo-800 rounded-full text-sm text-indigo-800">
        Hora de início: <span class="font-bold"><%= readable_time(@meeting.start_time) %></span>
      </p>
      <div class="border-t-2 border-indigo-800 border-dashed h-1 flex-1 text-gray-300">------</div>
      <p class="border-2 py-3 px-4 border-indigo-800 rounded-full text-sm text-indigo-800">
        Hora de terminio: <span class="font-bold"><%= readable_time(@meeting.end_time) %></span>
      </p>
    </div>

    <h4>Comentários</h4>
    <hr class="border" />

    <% unless user_signed_in? %>
      <div class="bg-gray-500 rounded p-4 mt-4 text-center">
        <p class="text-sm text-gray-900"><%= link_to "Login", new_user_session_path, class: "link" %> ou <%= link_to "Sign up", new_user_regsitration_path, class: "link" %> comentar.</p>
      </div>
    <% else %>
        <%= render 'comments/form' %>
    <% end %>

    <div id="comments">
      <%= render @meeting.comments %>
    </div>
  </div>
</div>

app/views/site/meeting/index.html.erb
<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
 <div class="dhx_cal_navline">
   <div class="dhx_cal_prev_button">&nbsp;</div>
   <div class="dhx_cal_next_button">&nbsp;</div>
   <div class="dhx_cal_today_button"></div>
   <div class="dhx_cal_date"></div>
   <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
   <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
   <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
 </div>
 <div class="dhx_cal_header">
 </div>
 <div class="dhx_cal_data">
 </div>
</div>

<script>
    scheduler.config.xml_date="%Y-%m-%d %H:%i";
    scheduler.init("scheduler_here");
    scheduler.load("<%= data_path %>", "json");
    var dp = new dataProcessor("<%= db_action_path %>");
    dp.init(scheduler);
    dp.setTransactionMode("GET", false);
</script>

app/views/users/shared/_form.html.erb
<div class="container">
        <div id="loginbox" style="<%= devise_sign_in? %> margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title"><%= t('labels.login') %></div>
                        <div style="float:right; font-size: 80%; position: relative; top:-18px">
                            <%= link_to t('labels.forgot_passoword'), new_user_password_path %>
                        </div>
                    </div>

                    <div style="padding-top:30px, color:white" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>


                        <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "form-horizontal", role:"form" }) do |f| %>

                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                        <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"#{t('labels.email')}", type: "email", autofocus: "autofocus" %>
                                    </div>

                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>

                                        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"#{t('labels.password')}", type:"password"  %>
                                    </div>



                            <div class="input-group">
                                      <div class="checkbox">
                                        <label>
                                          <% if devise_mapping.rememberable? -%>
                                              <%= f.check_box :remember_me %>
                                              <%= t('labels.remember_me') %>
                                          <% end -%>
                                        </label>
                                      </div>
                                    </div>


                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <%= f.submit (t('labels.enter')), class: "btn btn-success" %>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            <%= t('labels.dont_have_an_account') %>
                                        <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            <%= t('labels.sign_up_here') %>
                                        </a>
                                        </div>
                                    </div>
                                </div>
                            <% end %>



                        </div>
                    </div>
        </div>

        <div id="signupbox" style="<%= devise_sign_up? %> margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title"><%= t('labels.sign_up') %></div>
                            <div style="float:right; font-size: 85%; position: relative; top:-18px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()"><%= t('labels.login') %></a></div>
                        </div>
                        <div class="panel-body" >
                            <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: "form-horizontal", role:"form" }) do |f| %>

                                <div class="form-group">
                                    <%= f.label :email, class:"col-md-3 control-label" %>
                                    <div class="col-md-9">
                                        <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"#{t('labels.email')}", type: "email", autofocus: "autofocus" %>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= f.label :name, class:"col-md-3 control-label" %>
                                    <div class="col-md-9">
                                        <%= f.text_field :name, class:"form-control", placeholder:"Nome" %>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= f.label :password, class:"col-md-3 control-label" %>
                                    <div class="col-md-9">
                                        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"#{t('labels.password')}", type:"password" %>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <%= f.label :password_confirmation, class:"col-md-3 control-label" %>
                                    <div class="col-md-9">
                                        <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Confirmação da senha" %>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <!-- Button -->
                                    <div class="col-md-offset-3 col-md-9">
                                        <%= f.submit (t('labels.sign_up')), class: "btn btn-info" do %>
                                          <i class="icon-hand-right"></i> &nbsp Sign Up
                                        <% end %>
                                    </div>

                                </div>

                            <% end %>
                         </div>
                    </div>
         </div>
    </div>

<% flash.each do |key, value| %>
  <%= javascript_tag "$.notify( { message: '#{value}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
<% end %>
<% unless devise_error_messages!.blank? %>
  <% resource.errors.full_messages.each do |message| %>
      <%= javascript_tag "$.notify( { message: '#{message}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>